### ISSUE TITLE
Curious why this invocation for resolve

### ISSUE THREAD

**Issue by cahlan** [PWAckerman/didactic-meow#2]
https://github.com/PWAckerman/didactic-meow/blob/master/public/app.js#L127

**Comment by PWAckerman** [comment]
Not sure about this actually. Looks like inline annotation for dependency injection minification, but I don't think I used that anywhere else (like any of the other Auth resolves or in the controllers). I used a lot of code from AngularFire tutorials for authentication, so it might have been a copy-paste job. I'll have to see if it breaks when I take it out if I have time.

**Comment by cahlan** [comment]
yeah, typically this type of invocation is used to avoid problems when
minifying your JS. I figured it was something that snuck in there. And it's
not wrong (especially if you're minifying), I was just pointing it out.
